services:
  db:
    image: desafio-backend-db   
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
     TZ: "America/Sao_Paulo"
     POSTGRES_DB: mottu
     POSTGRES_ROOT_PASSWORD: postgres
     POSTGRES_USER: mUser
     POSTGRES_PASSWORD: mPass
    ports:
      - 3306:3306
    networks:
    - desafio-backend-net

  desafio-backend:
    image: desafio-backend
    build:
      context: .
      dockerfile: DesafioBackend/Dockerfile
    environment:
     TZ: "America/Sao_Paulo"
     ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    depends_on:
    - db
    networks:
    - desafio-backend-net
networks:
    desafio-backend-net:
        driver: bridge
