services:
  # db:
  #   image: desafio-backend-db   
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: db/Dockerfile
  #   environment:
  #    TZ: "America/Sao_Paulo"
  #    POSTGRES_DB: mottu
  #    POSTGRES_USER: mottuUser
  #    POSTGRES_PASSWORD: mottuPass
  #   ports:
  #     - 5433:5432
  #   networks:
  #   - desafio-backend-net

  desafio-backend:
    image: desafio-backend
    build:
      context: .
      dockerfile: DesafioBackend/Dockerfile
    environment:
     TZ: "America/Sao_Paulo"
     ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:8080
    # depends_on:
    # - db
    networks:
    - desafio-backend-net
networks:
    desafio-backend-net:
        driver: bridge
